# Generated by Django 4.1.3 on 2022-11-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(max_length=200)),
                ('zipcode', models.CharField(max_length=10)),
                ('skills', models.TextField(max_length=200)),
                ('git_username', models.CharField(max_length=200)),
                ('years_exp', models.CharField(max_length=3)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=200)),
                ('position_type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('preferred_skills', models.TextField()),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=200)),
                ('expiration_date', models.DateTimeField(verbose_name='expiration date')),
                ('status', models.CharField(max_length=200)),
                ('num_interested', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=300)),
                ('zipcode', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
