# Generated by Django 4.1.3 on 2022-12-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_post_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='bio',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_info', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('candidateOff', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.candidateprofile')),
                ('recruiterOff', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.recruiterprofile')),
            ],
        ),
    ]
