# Generated by Django 4.1.3 on 2022-12-04 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_candidateprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='postOff',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.post'),
        ),
    ]
