# Generated by Django 4.1.3 on 2022-12-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_offer_expired_offer_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='response',
            field=models.CharField(max_length=200),
        ),
    ]
